# Generated by Django 5.0.1 on 2024-03-01 16:10

import autoslug.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import django.db.models.manager
import store.utils.fileupload
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title')),
                ('image', models.ImageField(default='/Users/stevenchristian/Desktop/Code/astralis-commerce/commerce/media/placeholder/category.png', upload_to=store.utils.fileupload.user_directory_path)),
                ('cover_image', models.ImageField(default='/Users/stevenchristian/Desktop/Code/astralis-commerce/commerce/media/vendor-header-bg.png', upload_to=store.utils.fileupload.user_directory_path)),
                ('description', models.TextField(blank=True, default='Everyone has to face these problems.  When facing such problems, Understanding clearly what kind of existence the 69 is is the key to solving all problems.', null=True)),
                ('address', models.CharField(default='Jalan no 69', max_length=100)),
                ('contact', models.CharField(default='+62818181818', max_length=100)),
                ('chat_resp_time', models.CharField(default='100', max_length=100)),
                ('shipping_on_time', models.CharField(default='100', max_length=100)),
                ('authentic_rating', models.CharField(default='100', max_length=100)),
                ('days_return', models.CharField(default='100', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title')),
                ('title', models.CharField(default='The largest nuts in the world', max_length=100)),
                ('description', models.TextField(blank=True, default="The so-called Largest nuts, the key is how the Largest nuts needs to be written. So, So, With these questions, let's examine the Largest nuts.", max_length=255, null=True)),
                ('description_long', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='product long description', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='69000.00', max_digits=15)),
                ('old_price', models.DecimalField(decimal_places=2, default='69069.00', max_digits=15)),
                ('specification', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='product specification', null=True)),
                ('product_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('DISABLED', 'Disabled'), ('REJECTED', 'Rejected'), ('IN_REVIEW', 'In Review'), ('PUBLISHED', 'Published')], default='IN_REVIEW', max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('life', models.CharField(default='10 Days After Shipped', max_length=40)),
                ('mfd', models.DateTimeField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('is_digital', models.BooleanField(default=True)),
                ('sku', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.category')),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.vendor')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
