# Generated by Django 5.0.1 on 2024-03-01 16:51

import django.db.models.deletion
import modelcluster.fields
import store.utils.fileupload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_old_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to=store.utils.fileupload.product_gallery_image_upload_path)),
                ('product', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_gallery', to='store.product')),
            ],
            options={
                'verbose_name': 'product gallery',
                'verbose_name_plural': 'product gallery',
            },
        ),
    ]
