# Generated by Django 5.0.1 on 2024-03-01 16:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_managers_productgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
        migrations.AlterField(
            model_name='product',
            name='description_long',
            field=models.TextField(blank=True, default="The so-called Largest nuts, the key is how the Largest nuts needs to be written. So, So, With these questions, let's examine the Largest nuts.", max_length=1069, null=True),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('product', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_spec', to='store.product')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.spectable')),
            ],
        ),
    ]
