# Generated by Django 5.0.1 on 2024-03-02 18:28

import store.utils.fileupload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_product_is_digital_remove_product_life_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cover_image',
            field=models.ImageField(default='/Users/stevenchristian/Desktop/Code/astralis-commerce/commerce/media/vendor-header-bg.png', upload_to=store.utils.fileupload.user_directory_path),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='/Users/stevenchristian/Desktop/Code/astralis-commerce/commerce/media/placeholder/category.png', upload_to=store.utils.fileupload.user_directory_path),
        ),
    ]
