# Generated by Django 5.0.1 on 2024-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidercontent',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='slidercontent',
            name='title2',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
